version: '3'
services:

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    restart: always
    env_file: .env
    networks:
      - smartsoftlabs
    
  db:
    container_name: db
    restart: always
    env_file: .env
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - smartsoftlabs-data:/var/lib/postgresql/data
    networks:
      - smartsoftlabs

volumes:
  smartsoftlabs-data:
  

networks:
  smartsoftlabs:
    name: Smartsoftlabs
    driver: bridge